### ISSUE TITLE
Linking of IDM and LDAP users

### ISSUE THREAD

**Issue by mazah** [markusleh/django-real-open-idm-demo#4]
unique attribute should be used to link IDM and LDAP users.
username/samaccountname is not good enough since it can change.

Better alternative GUID  or objectSID
GUID is globally unique while objectSID only in the given AD environment

**Comment by markusleh** [comment]
As discussed, this is can already be achieved with `LDAP_USER_ATTRIBUTE`. However, this is valid when implemented with  #11
